n = 3
A = matrix(c(3,0,0,0,3,0,0,0,2), nrow=n, ncol=n)
print("The matrix is: ")
print(A)
eigens = eigen(A)
print("The eigen values are: ")
print(eigens$values)
print("The normalized eigen vectors are: ")
print(eigens$vectors)
sqrt_eigenvalues = sqrt(eigens$values)
print("The sqrt eigen values are: ")
print(sqrt_eigenvalues)
diag_matrix = diag(sqrt_eigenvalues)
print("The diagonal matrix is: ")
print(diag_matrix)
sqrt_matrix = eigens$vectors %*% diag_matrix %*% solve(eigens$vectors)

print("The required square root matrix of A is: ")
print(sqrt_matrix)
